name: Deploy buybay-api-users (EC2)

on:
  push:
    branches:
      - main
    paths:
      - ./**
      - '.github/workflows/buybay-api-users-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu/latest
    steps:
      - name: Print
        run: echo "Hello"
