name: Deploy buybay-api-users (EC2)

on:
  push:
    branches:
      - main
    paths:
      - ./**

jobs:
  deploy:
    runs-on: ubuntu/latest
    steps:
      - name: SSH into EC2
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
#          script: |
#            cd ~/buybay/buybay-api-users/
#            git pull origin main
#            echo "APP_KEY=${{ secrets.APP_KEY }}" > .env
#            echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}"  >> .env
#            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
#            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
#            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
#            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
#            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
#            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
#            echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
#            echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env
#            echo "FILESYSTEM_DISK=${{ secrets.FILESYSTEM_DISK }}" >> .env
#            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
#            echo "Deployed buybay-api-users"
#            cat .env
#            /vendor/bin/sail -f docker-compose.prod.yml up -d --build buybay-api-users
