name: Deploy buybay-api-users (EC2)

on:
  push:
    branches:
      - main
    paths:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Hello"
